Emitraw functions #69
altmp/altv-types pull request #102
Opened 2021-11-14 23:35 UTC by lilAmper

2021-11-14 23:36 UTC, C0kkie commented
Please also add, that emitServerRaw only works, if the server is using js

2021-11-14 23:42 UTC, C0kkie requested changes
Some small mistake

2021-11-14 23:42 UTC, C0kkie commented on docs/articles/understanding-events.md
> +    alt.emitClientRaw(player, 'sayHello', array);
Shouln't it be emitServerRaw here?

2021-11-15 15:48 UTC, LeonMrBonnie commented on docs/articles/understanding-events.md
> +| alt.emitClientRaw     | Emit big data an event to a specific client or an array of clients. It works faster than emitClient. That they receive with `alt.onServer`.    |
The sentence structure here is very weird

2021-11-15 15:49 UTC, LeonMrBonnie commented on docs/articles/understanding-events.md
> +| alt.emitAllClientsRaw | Emit big data an event to an event to all clients. It works faster than emitAllClients. That they receive with `alt.onServer`.                 |
Same problem as for emitClientRaw

2021-11-15 15:49 UTC, LeonMrBonnie commented on docs/articles/understanding-events.md
> +The server may only emit data to the client-side with `emitClient` and `emitClientRaw`, which requires a Player.
Use `or` instead of `and`

2021-11-15 15:50 UTC, LeonMrBonnie commented on docs/articles/understanding-events.md
> +`emitServerRaw` It is used for big data and is faster than `emitServer` and emitServerRaw only works, server is using js.
Weird sentence structure here again

2021-11-15 15:50 UTC, LeonMrBonnie commented
I think it may be worthwhile to add a whole section in this article dedicated to raw events, just to explain what they are and what they are for.

2021-11-15 19:20 UTC, C0kkie commented on docs/articles/events/index.md
> +***
For what are these 3 *

2021-11-15 19:27 UTC, LeonMrBonnie commented on docs/articles/events/index.md
> +    alt.emitClientRaw('sayHello', array);
emitAllClientsRaw typo

2021-11-15 19:46 UTC, C0kkie commented on docs/articles/events/index.md
> +```
add linebreak here

2021-11-15 19:46 UTC, C0kkie commented on docs/articles/events/index.md
> +```
add linebreak here

2021-11-15 19:47 UTC, C0kkie reviewed
Just 2 small things

2021-11-15 20:28 UTC, LeonMrBonnie commented on docs/articles/events/index.md
> +Raw event emitters are used in big data transfers.
The word emitters doesn't make sense here

2021-11-15 20:30 UTC, C0kkie commented on docs/articles/events/index.md
> +> [!WARNING]
CAUTION would here be better then a warning

2021-11-15 20:32 UTC, C0kkie commented on docs/articles/events/index.md
> +`emitClientRaw` and `emitAllClientsRaw` It is used for big data and is faster than `emitClient` or `emitAllClients`.
``are`` used for
and ``are`` faster than

2021-11-15 20:33 UTC, C0kkie commented on docs/articles/events/index.md
> +`emitServerRaw` It is used for big data and is faster than `emitServer` and emitServerRaw only works, the server is using js.
Just write

``is used for big data``

so remove the ``It``

2021-11-15 20:34 UTC, C0kkie commented on docs/articles/events/index.md
> +`emitServerRaw` It is used for big data and is faster than `emitServer` and emitServerRaw only works, the server is using js.
Also

only works, ``if`` the server is using js.

2021-11-15 20:48 UTC, C0kkie requested changes

2021-11-15 20:48 UTC, C0kkie commented on docs/articles/events/index.md
> +`emitServerRaw` It is used for big data and is faster than `emitServer` and emitServerRaw only works, if the server is using js.
Here is still the problem i already commented

Remove the ``it`` at the start behind ``emitServerRaw``

2021-11-15 20:48 UTC, C0kkie commented on docs/articles/events/index.md
> +`emitServerRaw` It is used for big data and is faster than `emitServer` and emitServerRaw only works, if the server is using js.
Also please write ``javascript`` instead of ``js``

2021-11-15 20:48 UTC, C0kkie commented on docs/articles/events/index.md
> +`emitServerRaw` It is used for big data and is faster than `emitServer` and emitServerRaw only works, if the server is using js.
```
than `emitServer` and emitServerRaw
```

Here is a quote missing for emitServerRaw

2021-11-15 21:14 UTC, C0kkie commented on docs/articles/events/index.md
> -***
add it back

2021-11-15 21:19 UTC, C0kkie commented
Thanks

2021-11-15 21:19 UTC, merged