Added kick reason and JSDoc to Player entity kick method type
altmp/altv-types pull request #2
Opened 2020-08-14 16:55 UTC by BKarner

2020-08-17 17:51 UTC, Lhoerion commented on server/index.d.ts
> +     * @param reason The reason to display to the player on the disconnect screen.
I think it should be more like
`The reason that will be displayed on the disconnect screen.`
or
`The reason that will display to the player on the disconnect screen.`

2020-08-17 17:52 UTC, Lhoerion commented on server/index.d.ts
> +     * Forcefully disconnects the player from the server with an error message.
It ain't an error message, so transform the sentence or remove this part.

2020-08-17 21:44 UTC, BKarner commented on server/index.d.ts
> +     * @param reason The reason to display to the player on the disconnect screen.
Changed it to the latter

2020-08-17 21:45 UTC, BKarner commented on server/index.d.ts
> +     * Forcefully disconnects the player from the server with an error message.
Changed it to "reason message" to match the parameter

2020-08-18 23:22 UTC, Lhoerion requested changes

2020-08-18 23:22 UTC, Lhoerion commented on server/index.d.ts
> +     * Forcefully disconnects the player from with a reason message.
There's a mistake here, lack of `the server` words between `from with`
edit: Or actually `from` word is obsolete there

2020-08-18 23:25 UTC, BKarner commented on server/index.d.ts
> +     * Forcefully disconnects the player from with a reason message.
Oh god yeah. Whoops

2020-08-19 12:23 UTC, Lhoerion approved these changes
Thanks for contribution, indeed I missed at some point that `kick` method lacks an parameter

2020-08-19 12:25 UTC, merged