Added more documentation to clientside and serverside
altmp/altv-types pull request #5
Opened 2020-08-22 08:15 UTC by LeonMrBonnie

2020-08-27 18:49 UTC, jovanivanovic requested changes

2020-08-27 18:49 UTC, jovanivanovic commented on client/index.d.ts
> +     * @remarks The color is a GTA hud color.
Could maybe add a link to the wiki topic where all the colors are defined?

2020-08-27 18:49 UTC, jovanivanovic commented on client/index.d.ts
> +     * Sprite of the blip.
Maybe add to remarks that this should be set first so it doesn't reset everything.

2020-08-27 18:49 UTC, jovanivanovic commented on client/index.d.ts
> +   * @returns Current game locale.
I am not sure which standard is used for locales, but I think that should be mentioned in the remarks here.

2020-08-27 18:49 UTC, jovanivanovic commented on server/index.d.ts
> +   * Vehicle neon.
This shouldn't be here.

2020-08-27 18:49 UTC, jovanivanovic commented on server/index.d.ts
> +   * RGBA Color.
Should set the ranges for each color (0-255) somewhere

2020-08-27 18:49 UTC, jovanivanovic commented on server/index.d.ts
> +     * @remarks A high ping is most often caused by a bad internet connection.
This is unnecessary info here.

2020-08-27 18:49 UTC, jovanivanovic commented on server/index.d.ts
> +     * @remarks This also sets the player health to max health
Maybe add a link here to `maxHealth`?

2020-08-27 18:49 UTC, jovanivanovic commented on server/index.d.ts
> +     * @remarks The color is a GTA hud color.
Maybe a link to wiki page where all the colors are defined?

2020-08-27 18:49 UTC, jovanivanovic commented on server/index.d.ts
> +     */
Add the `player` param description.

2020-08-27 18:49 UTC, jovanivanovic commented on server/index.d.ts
> +     */
For all methods in the `VoiceChannel` class

2020-08-27 18:53 UTC, LeonMrBonnie commented on client/index.d.ts
> +     * Sprite of the blip.
Actually I already added that, but it somehow slipped into the examples pr.

2020-08-27 18:54 UTC, LeonMrBonnie commented on client/index.d.ts
> +   * @returns Current game locale.
As found out in another PR recently, it just gives you the current alt:V locale. So it supports all the alt:V locales. But Lhoerion said he will create an enum for it, so I will leave this as it is.

2020-08-27 18:58 UTC, LeonMrBonnie commented on server/index.d.ts
> +   * RGBA Color.
I will add it as a remark to the constructor parameters. Typescript unfortunately doesn't support a number range as type.

2020-08-27 19:01 UTC, LeonMrBonnie commented on server/index.d.ts
> +     * @remarks The color is a GTA hud color.
Actually also that is wrong, because vehicle color is not hud color. But I fixed that already.

2020-08-30 00:09 UTC, Lhoerion requested changes
I review client-side part, but not entirely.
Some of the comments are done on basis of putting keyword inside a repeating sentence, not to mention that sometimes it lacked proper context. This needs to be changed.
Process of documenting stuff is slow, not to mention that it's being worked on only by me on regular basis and many of the information I need to get by hand or verify manually.
Keep up the work, I think after reading this and comments on your code you'll get what I mean and what I pursue

2020-08-30 00:09 UTC, Lhoerion commented on client/index.d.ts
> +   * @returns True if the game controls are enabled.
This is obsolete

2020-08-30 00:09 UTC, Lhoerion commented on client/index.d.ts
> +   * @returns A 2 dimensional vector representing the point on the screen where the cursor is located.
This is obsolete

2020-08-30 00:09 UTC, Lhoerion commented on client/index.d.ts
> +   * Gets a gxt label text.
This comment is not helpful at all

2020-08-30 00:09 UTC, Lhoerion commented on client/index.d.ts
> +   * Removes a gxt text label.
This comment is not helpful at all

2020-08-30 00:11 UTC, Lhoerion commented on client/index.d.ts
> +     * Sprite of the blip.
Then you need to add it back

2020-09-01 17:47 UTC, Lhoerion requested changes
Ok, I think we're getting there with client-side, tho all event comments weren't reviewed by me yet

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +     * Should the friend indicator on the blip be visible.
Remove it as well

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +     * GXT name of the blip.
I don't think remarks are actually properly stated

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +     * The color of the route to the blip.
Still no link

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +   * Gets a GXT label (localized string) to be used in natives.
You say label there, but in returns you mention value and I think you should stay with `value` keyword

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +   * Removes a GXT label (localized string) to be used in natives.
Same as above

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
>     * @remarks Can be set with {@link addGxtText}.
Can be added, but no mention of that it can be removed like below, oversight?

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +   * Creates a new GXT label (localized string) to be used in natives.
Read messages below

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +   * @remarks Gxt labels are used in some of the natives for displaying text. Can be get with {@link getGxtText}.
GXT needs to be upper-case, also it's not used in some natives, but it's used for ease translation into other languages

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +     * @remarks Accepted values are 0-255
No dot at the end

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +     * GXT name of the blip.
I think that for all gxt related signatures we could to something like `@see {@link article}` in the future, so we won't repeat ourselves

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +     * Heading (Yaw axis) of the blip.
Maybe change it to `yaw rotation` and should be ok now

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +     * The color of the route to the blip.
Also replace remarks with reminder that it needs to be set after `route` property

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +   * Executes a scaleform method on the minimap scaleform.
What do you think about omitting `scaleform` keyword that is before `method`?

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +   * @returns A 2 dimensional vector representing the point on the screen where the cursor is located.
Still remarks weren't removed

2020-09-01 17:47 UTC, Lhoerion commented on client/index.d.ts
> +   * @remarks Can be set with {@link setWeatherCycle}.
No, the weather can be set with said function

2020-09-02 11:40 UTC, Lhoerion commented on client/index.d.ts
> +     * The color of the route to the blip.
@LeonMrBonnie I said to replace, not to append
`See {@link https://wiki.altv.mp/Blips#Colors}` move to description

2020-09-02 12:02 UTC, Lhoerion commented on client/index.d.ts
> -   * @returns A 2 dimensional vector representing the point on the screen where the cursor is located.
I meant to remove `returns` tag only, I said that comment relates to line directly above it only

2020-09-02 14:35 UTC, Lhoerion commented on client/index.d.ts
> +   * Gets a GXT value (localized string) to be used in natives.
`to be used in natives` not necessary, it can be used everywhere

2020-09-02 15:03 UTC, Lhoerion commented on client/index.d.ts
>     * @remarks Can be set with {@link addGxtText}.
@LeonMrBonnie This too, I mean to add link to `removeGxtText`

2020-09-02 16:11 UTC, Lhoerion commented on client/index.d.ts
> +   * @remarks Can be set with {@link addGxtText}. Can be removed with {@link removeGxtText}.
`Can be set with {@link addGxtText} or removed with {@link removeGxtText}.`

2020-09-02 16:11 UTC, Lhoerion commented on client/index.d.ts
> +   * @remarks GXT values are used to localize strings into multiple languages. Can be get with {@link getGxtText}. Can be removed with {@link removeGxtText}.
`@remarks Can be get with {@link getGxtText} or removed with {@link removeGxtText}.

2020-09-02 16:12 UTC, Lhoerion commented on client/index.d.ts
>     * Creates a new GXT value (localized string).
`Creates a new GXT entry. (localized string)`

2020-09-02 16:13 UTC, Lhoerion commented on client/index.d.ts
>     * Gets a GXT value (localized string).
`Getsa a GXT value. (localized string)`

2020-09-02 16:13 UTC, Lhoerion commented on client/index.d.ts
>     * @returns GXT value.
Remove this line

2020-09-02 18:27 UTC, AlteredCarbonate requested changes
Stop using Gets fired...
For me, it doesn't sound good formulated

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +     * Should the blip be bright.
I don't know mate, why you always saying Should?
Incorrectly formulated

Just say "Sets the blips brighter"

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +     * Should the heading indicator on the blip be visible.
Stop using Should

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +     * Should the route to the blip be displayed on the map.
Stop using Should

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +     * Should the blip be short range.
Stop using Should

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +     * Should the blip be shrinked.
Stop using Should

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +     * Fades the blip to the specified opacity for the specified amount of time.
for the specified amount of time.
for a specified amount of time.

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when an error occurs on any resource.
Fires when an error occurs on any resource.

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when any resource starts.
Called when any resource starts

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when any resource stops.
Called when any resource stops.

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when a command is entered into the client console. (F8)
Called when a command is entered into the client console. (F8)

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when the local player disconnects from the server.
Called when the local player disconnects from the server.

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when a game entity (e.g. a vehicle) gets created in the world.
Called when a game entity (e.g. a vehicle) gets created in the world.

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when a game entity (e.g. a vehicle) gets removed from the world.
Called when a game entity (e.g. a vehicle) gets removed from the world.

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when you press down on a button.
Called on keydown

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when you release a button.
Called on keyup ( Release of Key)

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when the resource starts.
Called when the resource starts.

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when an entity gets completely removed.
Called when an entity gets completely removed.

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when the resource stops.
Called when the resource stops.

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when the synced meta on any entity has changed.
Called when the synced meta on any entity has changed

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when the stream synced meta on any entity has changed.
Called when the stream synced meta on any entity has changed.

2020-09-02 18:27 UTC, AlteredCarbonate commented on client/index.d.ts
> +   * Gets fired when any global meta has changed.
Called when any global meta has changed.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +     * The vehicle neon layout.
Linking to the Neon interface?
Maybe it's not possible and I'm missing something out

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +     * Sets the mod in the specified category.
Sets the mod of a specified category.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when an error occurs on any resource.
Called when an error occurs on any resource.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when any resource starts.
Called when any resource starts.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when any resource stops.
Called when any resource stops.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when a command gets entered into the server console.
Called when a command gets entered into the server console.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when an entity enters a colshape.
Called when an entity enters a colshape.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when an entity leaves a colshape.
Called when an entity leaves a colshape.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when an explosion gets created.
Called when an explosion gets created.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when a player changes their vehicle seat.
Called when a player changes their vehicle seat.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when a player connects.
Called when a player connects.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when a player gets damaged.
Called when a player gets damaged.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when a player dies.
Called when a player dies.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when a player disconnects.
Called when a player disconnects.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when a player enters a vehicle.
Called when a player enters a vehicle.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when a player leaves a vehicle.
Called when a player leaves a vehicle.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when an entity gets removed. Usually with the {@link BaseObject.destroy} method.
Called when an entity gets removed. Usually with the {@link BaseObject.destroy} method.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when the resource starts.
Called when the resource starts.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when the resource stops.
Called when the resource stops.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when the synced meta on any entity has changed.
Called when the synced meta on any entity has changed.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when the stream synced meta on any entity has changed.
Called when the stream synced meta on any entity has changed.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when any global meta has changed.
Called when any global meta has changed.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when any global synced meta has changed.
Called when any global synced meta has changed.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when a vehicle gets destroyed.
Called when a vehicle gets destroyed.

2020-09-02 18:27 UTC, AlteredCarbonate commented on server/index.d.ts
> +   * Gets fired when a player gets damaged by any source.
Called when a player gets damaged by any source.

2020-09-02 23:14 UTC, Lhoerion commented on client/index.d.ts
> +   * Prints the arguments to the ingame console as a warning. (F8)
I'd suggest something like `Outputs a warning message to the in-game console.`

2020-09-02 23:15 UTC, Lhoerion commented on client/index.d.ts
> +   * Prints the arguments to the ingame console as an error. (F8)
I'd suggest something like `Outputs an error message to the in-game console.`

2020-09-02 23:15 UTC, Lhoerion commented on client/index.d.ts
> +   * Prints the arguments to the ingame console. (F8)
I'd suggest something like `Outputs a message to the in-game console.`

2020-09-03 17:36 UTC, Lhoerion commented on server/index.d.ts
> +     * The vehicle neon layout.
It's linked already in return type of the signature

2021-01-20 18:54 UTC, closed without merging