Update config flag function descriptions and add ped config flags enum
altmp/altv-types pull request #57
Opened 2021-03-13 10:36 UTC by TheMysteriousVincent

2021-03-13 10:37 UTC, TheMysteriousVincent commented
Note: Accidentally some CRLFs were converted to LF

2021-03-13 10:40 UTC, LeonMrBonnie commented on client/index.d.ts
> +  export const enum PedConfigFlagNames {
Please change the name to something shorter like `PedConfigFlags`

2021-03-13 10:40 UTC, LeonMrBonnie commented on client/index.d.ts
>    export function setConfigFlag(flag: string, state: boolean): void;
Use the enum you added here as a type for the `flag` param.

2021-03-13 10:40 UTC, LeonMrBonnie commented on client/index.d.ts
>    export function setConfigFlag(flag: string, state: boolean): void;
The same for all the other two config flag related functions.

2021-03-13 18:57 UTC, LeonMrBonnie commented on client/index.d.ts
> +   *
Remove this newline here

2021-03-13 18:57 UTC, LeonMrBonnie commented on client/index.d.ts
> +   *
Also on the other TSDoc comments you made

2021-03-13 19:11 UTC, TheMysteriousVincent commented on client/index.d.ts
> +   *
@LeonMrBonnie What's the reason for that? In general a double newline represents a line break which is intended by me.

2021-03-14 11:21 UTC, Lhoerion commented
I'm not entirely convinced that such enum like here is worth adding, when it's much likely to change every GTA update and yet it's not complete list

2021-03-14 11:22 UTC, TheMysteriousVincent commented
> I'm not entirely convinced that such enum like here is worth adding, when it's much likely to change every GTA update and yet it's not complete list

Do the names change? I don't think so, isn't it?

2021-03-14 13:19 UTC, LeonMrBonnie commented on client/index.d.ts
> +   *
I meant to remove the empty line there, to conform with the rest of the documentation

2021-03-14 13:20 UTC, LeonMrBonnie commented
> 
> 
> I'm not entirely convinced that such enum like here is worth adding, when it's much likely to change every GTA update and yet it's not complete list

They haven't changed before so I don't think they will ever change, I mean why would they. I think it's fine to add an enum like that even if it's not complete.

2021-03-14 13:24 UTC, TheMysteriousVincent commented on client/index.d.ts
> +   *
I know, but that empty line represents a line break in a description. For example, if I write
```
/*
 * Test.
 * test
 */
```
the result would be `Test. test` when generated.

When writing two line breaks in the description, it will result in an line break in the documentation:
```
/*
 * Test.
 *
 * test
 */
```
results in
```
Test.
test
```

2021-03-14 13:26 UTC, TheMysteriousVincent commented on client/index.d.ts
> +   *
@LeonMrBonnie Its about having a fine formatted description. Nobody wants to read full text without line breaks when the text content is not coherent :)

2021-03-14 14:14 UTC, LeonMrBonnie commented on client/index.d.ts
> +   *
Ah yes you are right, mb.

2021-03-15 13:58 UTC, LeonMrBonnie commented on client/index.d.ts
> +   * See this list for reference: https://wiki.altv.mp/wiki/GTA:Ped_Config_Flags
Put this into the `@remarks` field

2021-03-15 14:10 UTC, TheMysteriousVincent commented on client/index.d.ts
> +   * See this list for reference: https://wiki.altv.mp/wiki/GTA:Ped_Config_Flags
Good idea.

2021-03-15 14:22 UTC, LeonMrBonnie approved these changes

2021-03-16 01:12 UTC, FabianTerhorst approved these changes

2021-03-16 22:40 UTC, FabianTerhorst commented on client/index.d.ts
> +    DisablePropKnockOff = "PED_FLAG_DISABLE_PROP_KNOCK_OFF",
this is the only value that works with it.
You have to remove all other values from the enum.

2021-03-16 22:41 UTC, FabianTerhorst requested changes
Remove the none supported ped config flags from the enum

2021-03-16 22:43 UTC, Lhoerion commented
Internally it was confirmed, that only one flag works.
So if you want still to make changes to this PR:
* remove link to wiki
* remove enum
* change flag parameter type from string to that string literal

2021-03-16 23:07 UTC, TheMysteriousVincent commented
Alright, good to know.

Fixed that so far with two side notes:
* I renamed `PedConfigFlags` to `PedConfigFlag` for a more precise naming
* `string | PedConfigFlag` type is needed as some JS/TS (trans-)compiler do not substitute enum values when ignoring the `alt-client` module (e.g. when using bundlers).

2021-03-17 11:25 UTC, Lhoerion commented
Enum for this one flag isn't needed, just replace it with string literal, as only one flag is valid for this function

2021-03-17 13:05 UTC, TheMysteriousVincent commented
> Enum for this one flag isn't needed, just replace it with string literal, as only one flag is valid for this function

@Lhoerion I get your point, though I think it is more clever to "outsource" the flags to another datatype, because then it would be more easily to maintain (e.g. adding or removing flags).

2021-03-17 23:11 UTC, vadzz-dev commented
It actually not related to ped at all, just some random global flags

2021-03-17 23:14 UTC, vadzz-dev commented
Not sure where did you get name, but the only existing flag is `DISABLE_PED_PROP_KNOCK_OFF`

2021-03-17 23:18 UTC, TheMysteriousVincent commented
> Not sure where did you get name, but the only existing flag is `DISABLE_PED_PROP_KNOCK_OFF`. It globally disables knock off for all peds

@vadzz-dev sauce: https://wiki.altv.mp/wiki/GTA:Ped_Config_Flags

2021-03-17 23:24 UTC, vadzz-dev commented
This function is not related to that list in any way. It was made for random stuff that can't be achieved with natives

2021-03-17 23:26 UTC, TheMysteriousVincent commented
> This function is not related to that list in any way. It was made for random stuff that can't be achieved with natives

@vadzz-dev Then the documentation was bad all the time. I fix that in a second

2021-03-19 02:16 UTC, Lhoerion commented
> @vadzz-dev Then the documentation was bad all the time. I fix that in a second

It wasn't bad

2021-03-19 02:21 UTC, Lhoerion requested changes
> @vadzz-dev Then the documentation was bad all the time. I fix that in a second

It wasn't bad

PS

Change single qutoes to double quotes (and flag to the one VadZz has provided)

2021-03-19 13:04 UTC, Lhoerion approved these changes
> > Enum for this one flag isn't needed, just replace it with string literal, as only one flag is valid for this function
> 
> @Lhoerion I get your point, though I think it is more clever to "outsource" the flags to another datatype, because then it would be more easily to maintain (e.g. adding or removing flags).

Yes, we'd do that for any other type, but in this case it'd be nonsense, since I don't think any other flag will be added in the nearest future

Thanks for contribution, appreciated

2021-03-19 13:05 UTC, LeonMrBonnie approved these changes

2021-03-19 13:07 UTC, merged