add localstorage article
altmp/altv-types pull request #59
Opened 2021-03-31 12:08 UTC by DerGonzi

isnt add to toc.yml -> open via http://localhost:8080/js/articles/player/client/localstorage.html

2021-03-31 12:11 UTC, LeonMrBonnie commented
I think you should add a comment explicitly telling not to use LocalStorage for sensitive data.

2021-03-31 12:19 UTC, DerGonzi commented
> I think you should add a comment explicitly telling not to use LocalStorage for sensitive data.

good idea

2021-03-31 12:24 UTC, LeonMrBonnie commented on docs/articles/player/client/localstorage.md
> +import alt from "alt-client";
`import * as alt from "alt-client"`
It is recommended to use named import instead of default import.

2021-03-31 12:24 UTC, LeonMrBonnie commented on docs/articles/player/client/localstorage.md
> +A General Overview
Make this a heading
`## A General Overview`

2021-03-31 12:24 UTC, LeonMrBonnie commented on docs/articles/player/client/localstorage.md
> +Example use cases:
Make this a heading
`## Example use cases`

2021-03-31 12:31 UTC, DerGonzi commented on docs/articles/player/client/localstorage.md
> +import alt from "alt-client";
Thx

2021-04-01 10:38 UTC, LeonMrBonnie approved these changes

2021-04-05 13:11 UTC, Lhoerion requested changes
For now it can go under Getting Started category as last entry @DerGonzi

2021-04-07 14:45 UTC, DerGonzi commented
> For now it can go under Getting Started category as last entry @DerGonzi

Done @Lhoerion

2021-04-07 15:46 UTC, DerGonzi reviewed
changed

2021-04-08 00:41 UTC, Lhoerion commented
ToC title as `Local Storage` or `Local storage` @DerGonzi

2021-04-08 01:22 UTC, merged