feat(): add missing types for indicator lights, fix(): wrong maxGear tag
altmp/altv-types pull request #74
Opened 2021-06-21 19:52 UTC by tastydev

2021-06-21 19:55 UTC, LeonMrBonnie requested changes
Please specify the indicatorLights property like all other properties

2021-06-21 20:03 UTC, LeonMrBonnie commented on client/index.d.ts
> +     * Vehicle indicator lights
Missing a `.` at the end
Maybe also add something like `state`

2021-06-21 20:07 UTC, LeonMrBonnie commented on client/index.d.ts
> +     * Set & get the state for indicator lights.
Just remove this line, its not needed

2021-06-21 20:59 UTC, LeonMrBonnie approved these changes

2021-06-22 23:46 UTC, Lhoerion approved these changes
Thanks!

2021-06-22 23:48 UTC, merged